/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.platoon.impl;

import nl.tue.glt.platoon.PlatoonPackage;
import nl.tue.glt.platoon.Turn;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Turn</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TurnImpl extends ActionImpl implements Turn
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TurnImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PlatoonPackage.Literals.TURN;
  }

} //TurnImpl
