/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.scoping;

import nl.tue.glt.scoping.AbstractBoundingBoxScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class BoundingBoxScopeProvider extends AbstractBoundingBoxScopeProvider {
}
