/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.platoon;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraints</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.tue.glt.platoon.Constraints#getMinHeadway <em>Min Headway</em>}</li>
 *   <li>{@link nl.tue.glt.platoon.Constraints#getMaxHeadway <em>Max Headway</em>}</li>
 * </ul>
 *
 * @see nl.tue.glt.platoon.PlatoonPackage#getConstraints()
 * @model
 * @generated
 */
public interface Constraints extends EObject
{
  /**
   * Returns the value of the '<em><b>Min Headway</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Min Headway</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min Headway</em>' attribute.
   * @see #setMinHeadway(int)
   * @see nl.tue.glt.platoon.PlatoonPackage#getConstraints_MinHeadway()
   * @model
   * @generated
   */
  int getMinHeadway();

  /**
   * Sets the value of the '{@link nl.tue.glt.platoon.Constraints#getMinHeadway <em>Min Headway</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min Headway</em>' attribute.
   * @see #getMinHeadway()
   * @generated
   */
  void setMinHeadway(int value);

  /**
   * Returns the value of the '<em><b>Max Headway</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Max Headway</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Headway</em>' attribute.
   * @see #setMaxHeadway(int)
   * @see nl.tue.glt.platoon.PlatoonPackage#getConstraints_MaxHeadway()
   * @model
   * @generated
   */
  int getMaxHeadway();

  /**
   * Sets the value of the '{@link nl.tue.glt.platoon.Constraints#getMaxHeadway <em>Max Headway</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Headway</em>' attribute.
   * @see #getMaxHeadway()
   * @generated
   */
  void setMaxHeadway(int value);

} // Constraints
