/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.platoon;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Left</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.tue.glt.platoon.PlatoonPackage#getLeft()
 * @model
 * @generated
 */
public interface Left extends Turn
{
} // Left
