/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.platoon;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Platoon</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.tue.glt.platoon.Platoon#getFirst <em>First</em>}</li>
 *   <li>{@link nl.tue.glt.platoon.Platoon#getFollowers <em>Followers</em>}</li>
 * </ul>
 *
 * @see nl.tue.glt.platoon.PlatoonPackage#getPlatoon()
 * @model
 * @generated
 */
public interface Platoon extends EObject
{
  /**
   * Returns the value of the '<em><b>First</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>First</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>First</em>' containment reference.
   * @see #setFirst(LV)
   * @see nl.tue.glt.platoon.PlatoonPackage#getPlatoon_First()
   * @model containment="true"
   * @generated
   */
  LV getFirst();

  /**
   * Sets the value of the '{@link nl.tue.glt.platoon.Platoon#getFirst <em>First</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First</em>' containment reference.
   * @see #getFirst()
   * @generated
   */
  void setFirst(LV value);

  /**
   * Returns the value of the '<em><b>Followers</b></em>' containment reference list.
   * The list contents are of type {@link nl.tue.glt.platoon.FV}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Followers</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Followers</em>' containment reference list.
   * @see nl.tue.glt.platoon.PlatoonPackage#getPlatoon_Followers()
   * @model containment="true"
   * @generated
   */
  EList<FV> getFollowers();

} // Platoon
