/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.platoon;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Right</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.tue.glt.platoon.PlatoonPackage#getRight()
 * @model
 * @generated
 */
public interface Right extends Turn
{
} // Right
