/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.platoon;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Turn</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.tue.glt.platoon.PlatoonPackage#getTurn()
 * @model
 * @generated
 */
public interface Turn extends Action
{
} // Turn
