/*
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.ui.tests;

import a4_bounding.ui.internal.A4_boundingActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class BoundingBoxUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return A4_boundingActivator.getInstance().getInjector("nl.tue.glt.BoundingBox");
	}

}
