grammar nl.tue.glt.BoundingBox with org.eclipse.xtext.common.Terminals

generate boundingBox "http://www.tue.nl/glt/BoundingBox"

World: {World}
	'Box:' '\n'
		moveCommands+=Move*;
Move:
	MoveX | MoveY;

MoveX:
	MoveLeft | MoveRight;

MoveY:
	MoveUp | MoveDown;

MoveLeft:
	'left' distance=INT '\n';

MoveRight:
	'right' distance=INT '\n';

MoveUp:
	'up' distance=INT '\n';

MoveDown:
	'down' distance=INT '\n';