/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.boundingBox.impl;

import nl.tue.glt.boundingBox.BoundingBoxFactory;
import nl.tue.glt.boundingBox.BoundingBoxPackage;
import nl.tue.glt.boundingBox.Move;
import nl.tue.glt.boundingBox.MoveDown;
import nl.tue.glt.boundingBox.MoveLeft;
import nl.tue.glt.boundingBox.MoveRight;
import nl.tue.glt.boundingBox.MoveUp;
import nl.tue.glt.boundingBox.MoveX;
import nl.tue.glt.boundingBox.MoveY;
import nl.tue.glt.boundingBox.World;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class BoundingBoxPackageImpl extends EPackageImpl implements BoundingBoxPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass worldEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass moveEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass moveXEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass moveYEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass moveLeftEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass moveRightEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass moveUpEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass moveDownEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see nl.tue.glt.boundingBox.BoundingBoxPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private BoundingBoxPackageImpl()
  {
    super(eNS_URI, BoundingBoxFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link BoundingBoxPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static BoundingBoxPackage init()
  {
    if (isInited) return (BoundingBoxPackage)EPackage.Registry.INSTANCE.getEPackage(BoundingBoxPackage.eNS_URI);

    // Obtain or create and register package
    BoundingBoxPackageImpl theBoundingBoxPackage = (BoundingBoxPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof BoundingBoxPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new BoundingBoxPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theBoundingBoxPackage.createPackageContents();

    // Initialize created meta-data
    theBoundingBoxPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theBoundingBoxPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(BoundingBoxPackage.eNS_URI, theBoundingBoxPackage);
    return theBoundingBoxPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWorld()
  {
    return worldEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getWorld_MoveCommands()
  {
    return (EReference)worldEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMove()
  {
    return moveEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMove_Distance()
  {
    return (EAttribute)moveEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMoveX()
  {
    return moveXEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMoveY()
  {
    return moveYEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMoveLeft()
  {
    return moveLeftEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMoveRight()
  {
    return moveRightEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMoveUp()
  {
    return moveUpEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMoveDown()
  {
    return moveDownEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BoundingBoxFactory getBoundingBoxFactory()
  {
    return (BoundingBoxFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    worldEClass = createEClass(WORLD);
    createEReference(worldEClass, WORLD__MOVE_COMMANDS);

    moveEClass = createEClass(MOVE);
    createEAttribute(moveEClass, MOVE__DISTANCE);

    moveXEClass = createEClass(MOVE_X);

    moveYEClass = createEClass(MOVE_Y);

    moveLeftEClass = createEClass(MOVE_LEFT);

    moveRightEClass = createEClass(MOVE_RIGHT);

    moveUpEClass = createEClass(MOVE_UP);

    moveDownEClass = createEClass(MOVE_DOWN);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    moveXEClass.getESuperTypes().add(this.getMove());
    moveYEClass.getESuperTypes().add(this.getMove());
    moveLeftEClass.getESuperTypes().add(this.getMoveX());
    moveRightEClass.getESuperTypes().add(this.getMoveX());
    moveUpEClass.getESuperTypes().add(this.getMoveY());
    moveDownEClass.getESuperTypes().add(this.getMoveY());

    // Initialize classes and features; add operations and parameters
    initEClass(worldEClass, World.class, "World", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getWorld_MoveCommands(), this.getMove(), null, "moveCommands", null, 0, -1, World.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(moveEClass, Move.class, "Move", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMove_Distance(), ecorePackage.getEInt(), "distance", null, 0, 1, Move.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(moveXEClass, MoveX.class, "MoveX", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(moveYEClass, MoveY.class, "MoveY", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(moveLeftEClass, MoveLeft.class, "MoveLeft", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(moveRightEClass, MoveRight.class, "MoveRight", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(moveUpEClass, MoveUp.class, "MoveUp", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(moveDownEClass, MoveDown.class, "MoveDown", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    // Create resource
    createResource(eNS_URI);
  }

} //BoundingBoxPackageImpl
