/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.boundingBox.impl;

import java.util.Collection;

import nl.tue.glt.boundingBox.BoundingBoxPackage;
import nl.tue.glt.boundingBox.Model;
import nl.tue.glt.boundingBox.Move;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link nl.tue.glt.boundingBox.impl.ModelImpl#getMoveCommands <em>Move Commands</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelImpl extends MinimalEObjectImpl.Container implements Model
{
  /**
   * The cached value of the '{@link #getMoveCommands() <em>Move Commands</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMoveCommands()
   * @generated
   * @ordered
   */
  protected EList<Move> moveCommands;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BoundingBoxPackage.Literals.MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Move> getMoveCommands()
  {
    if (moveCommands == null)
    {
      moveCommands = new EObjectContainmentEList<Move>(Move.class, this, BoundingBoxPackage.MODEL__MOVE_COMMANDS);
    }
    return moveCommands;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BoundingBoxPackage.MODEL__MOVE_COMMANDS:
        return ((InternalEList<?>)getMoveCommands()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BoundingBoxPackage.MODEL__MOVE_COMMANDS:
        return getMoveCommands();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BoundingBoxPackage.MODEL__MOVE_COMMANDS:
        getMoveCommands().clear();
        getMoveCommands().addAll((Collection<? extends Move>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BoundingBoxPackage.MODEL__MOVE_COMMANDS:
        getMoveCommands().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BoundingBoxPackage.MODEL__MOVE_COMMANDS:
        return moveCommands != null && !moveCommands.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ModelImpl
