/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.boundingBox.impl;

import nl.tue.glt.boundingBox.BoundingBoxPackage;
import nl.tue.glt.boundingBox.MoveY;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Move Y</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MoveYImpl extends MoveImpl implements MoveY
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MoveYImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BoundingBoxPackage.Literals.MOVE_Y;
  }

} //MoveYImpl
