/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.boundingBox.impl;

import nl.tue.glt.boundingBox.BoundingBoxPackage;
import nl.tue.glt.boundingBox.MoveLeft;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Move Left</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MoveLeftImpl extends MoveXImpl implements MoveLeft
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MoveLeftImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BoundingBoxPackage.Literals.MOVE_LEFT;
  }

} //MoveLeftImpl
