/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.boundingBox.impl;

import nl.tue.glt.boundingBox.BoundingBoxPackage;
import nl.tue.glt.boundingBox.MoveRight;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Move Right</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MoveRightImpl extends MoveXImpl implements MoveRight
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MoveRightImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BoundingBoxPackage.Literals.MOVE_RIGHT;
  }

} //MoveRightImpl
