/*
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.ui.tests;

import a4_platoon.ui.internal.A4_platoonActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class PlatoonUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return A4_platoonActivator.getInstance().getInjector("nl.tue.glt.Platoon");
	}

}
