<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="boundingbox" nsURI="boundingbox" nsPrefix="boundingbox">
  <eClassifiers xsi:type="ecore:EClass" name="Move" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveX" abstract="true" eSuperTypes="#//Move"/>
  <eClassifiers xsi:type="ecore:EClass" name="MoveY" abstract="true" eSuperTypes="#//Move"/>
  <eClassifiers xsi:type="ecore:EClass" name="MoveLeft" eSuperTypes="#//MoveX"/>
  <eClassifiers xsi:type="ecore:EClass" name="MoveRight" eSuperTypes="#//MoveX"/>
  <eClassifiers xsi:type="ecore:EClass" name="MoveUp" eSuperTypes="#//MoveY"/>
  <eClassifiers xsi:type="ecore:EClass" name="MoveDown" eSuperTypes="#//MoveY"/>
  <eClassifiers xsi:type="ecore:EClass" name="World">
    <eStructuralFeatures xsi:type="ecore:EReference" name="moveCommands" upperBound="-1"
        eType="#//Move" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
