/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.boundingBox;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see nl.tue.glt.boundingBox.BoundingBoxFactory
 * @model kind="package"
 * @generated
 */
public interface BoundingBoxPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "boundingBox";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.tue.nl/glt/BoundingBox";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "boundingBox";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BoundingBoxPackage eINSTANCE = nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl.init();

  /**
   * The meta object id for the '{@link nl.tue.glt.boundingBox.impl.WorldImpl <em>World</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.glt.boundingBox.impl.WorldImpl
   * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getWorld()
   * @generated
   */
  int WORLD = 0;

  /**
   * The feature id for the '<em><b>Move Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORLD__MOVE_COMMANDS = 0;

  /**
   * The number of structural features of the '<em>World</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORLD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link nl.tue.glt.boundingBox.impl.MoveImpl <em>Move</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.glt.boundingBox.impl.MoveImpl
   * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getMove()
   * @generated
   */
  int MOVE = 1;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__DISTANCE = 0;

  /**
   * The number of structural features of the '<em>Move</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link nl.tue.glt.boundingBox.impl.MoveXImpl <em>Move X</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.glt.boundingBox.impl.MoveXImpl
   * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getMoveX()
   * @generated
   */
  int MOVE_X = 2;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_X__DISTANCE = MOVE__DISTANCE;

  /**
   * The number of structural features of the '<em>Move X</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_X_FEATURE_COUNT = MOVE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link nl.tue.glt.boundingBox.impl.MoveYImpl <em>Move Y</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.glt.boundingBox.impl.MoveYImpl
   * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getMoveY()
   * @generated
   */
  int MOVE_Y = 3;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_Y__DISTANCE = MOVE__DISTANCE;

  /**
   * The number of structural features of the '<em>Move Y</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_Y_FEATURE_COUNT = MOVE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link nl.tue.glt.boundingBox.impl.MoveLeftImpl <em>Move Left</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.glt.boundingBox.impl.MoveLeftImpl
   * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getMoveLeft()
   * @generated
   */
  int MOVE_LEFT = 4;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_LEFT__DISTANCE = MOVE_X__DISTANCE;

  /**
   * The number of structural features of the '<em>Move Left</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_LEFT_FEATURE_COUNT = MOVE_X_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link nl.tue.glt.boundingBox.impl.MoveRightImpl <em>Move Right</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.glt.boundingBox.impl.MoveRightImpl
   * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getMoveRight()
   * @generated
   */
  int MOVE_RIGHT = 5;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_RIGHT__DISTANCE = MOVE_X__DISTANCE;

  /**
   * The number of structural features of the '<em>Move Right</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_RIGHT_FEATURE_COUNT = MOVE_X_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link nl.tue.glt.boundingBox.impl.MoveUpImpl <em>Move Up</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.glt.boundingBox.impl.MoveUpImpl
   * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getMoveUp()
   * @generated
   */
  int MOVE_UP = 6;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_UP__DISTANCE = MOVE_Y__DISTANCE;

  /**
   * The number of structural features of the '<em>Move Up</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_UP_FEATURE_COUNT = MOVE_Y_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link nl.tue.glt.boundingBox.impl.MoveDownImpl <em>Move Down</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see nl.tue.glt.boundingBox.impl.MoveDownImpl
   * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getMoveDown()
   * @generated
   */
  int MOVE_DOWN = 7;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_DOWN__DISTANCE = MOVE_Y__DISTANCE;

  /**
   * The number of structural features of the '<em>Move Down</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_DOWN_FEATURE_COUNT = MOVE_Y_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link nl.tue.glt.boundingBox.World <em>World</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>World</em>'.
   * @see nl.tue.glt.boundingBox.World
   * @generated
   */
  EClass getWorld();

  /**
   * Returns the meta object for the containment reference list '{@link nl.tue.glt.boundingBox.World#getMoveCommands <em>Move Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Move Commands</em>'.
   * @see nl.tue.glt.boundingBox.World#getMoveCommands()
   * @see #getWorld()
   * @generated
   */
  EReference getWorld_MoveCommands();

  /**
   * Returns the meta object for class '{@link nl.tue.glt.boundingBox.Move <em>Move</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move</em>'.
   * @see nl.tue.glt.boundingBox.Move
   * @generated
   */
  EClass getMove();

  /**
   * Returns the meta object for the attribute '{@link nl.tue.glt.boundingBox.Move#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see nl.tue.glt.boundingBox.Move#getDistance()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Distance();

  /**
   * Returns the meta object for class '{@link nl.tue.glt.boundingBox.MoveX <em>Move X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move X</em>'.
   * @see nl.tue.glt.boundingBox.MoveX
   * @generated
   */
  EClass getMoveX();

  /**
   * Returns the meta object for class '{@link nl.tue.glt.boundingBox.MoveY <em>Move Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move Y</em>'.
   * @see nl.tue.glt.boundingBox.MoveY
   * @generated
   */
  EClass getMoveY();

  /**
   * Returns the meta object for class '{@link nl.tue.glt.boundingBox.MoveLeft <em>Move Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move Left</em>'.
   * @see nl.tue.glt.boundingBox.MoveLeft
   * @generated
   */
  EClass getMoveLeft();

  /**
   * Returns the meta object for class '{@link nl.tue.glt.boundingBox.MoveRight <em>Move Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move Right</em>'.
   * @see nl.tue.glt.boundingBox.MoveRight
   * @generated
   */
  EClass getMoveRight();

  /**
   * Returns the meta object for class '{@link nl.tue.glt.boundingBox.MoveUp <em>Move Up</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move Up</em>'.
   * @see nl.tue.glt.boundingBox.MoveUp
   * @generated
   */
  EClass getMoveUp();

  /**
   * Returns the meta object for class '{@link nl.tue.glt.boundingBox.MoveDown <em>Move Down</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move Down</em>'.
   * @see nl.tue.glt.boundingBox.MoveDown
   * @generated
   */
  EClass getMoveDown();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BoundingBoxFactory getBoundingBoxFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link nl.tue.glt.boundingBox.impl.WorldImpl <em>World</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.glt.boundingBox.impl.WorldImpl
     * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getWorld()
     * @generated
     */
    EClass WORLD = eINSTANCE.getWorld();

    /**
     * The meta object literal for the '<em><b>Move Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORLD__MOVE_COMMANDS = eINSTANCE.getWorld_MoveCommands();

    /**
     * The meta object literal for the '{@link nl.tue.glt.boundingBox.impl.MoveImpl <em>Move</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.glt.boundingBox.impl.MoveImpl
     * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getMove()
     * @generated
     */
    EClass MOVE = eINSTANCE.getMove();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__DISTANCE = eINSTANCE.getMove_Distance();

    /**
     * The meta object literal for the '{@link nl.tue.glt.boundingBox.impl.MoveXImpl <em>Move X</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.glt.boundingBox.impl.MoveXImpl
     * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getMoveX()
     * @generated
     */
    EClass MOVE_X = eINSTANCE.getMoveX();

    /**
     * The meta object literal for the '{@link nl.tue.glt.boundingBox.impl.MoveYImpl <em>Move Y</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.glt.boundingBox.impl.MoveYImpl
     * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getMoveY()
     * @generated
     */
    EClass MOVE_Y = eINSTANCE.getMoveY();

    /**
     * The meta object literal for the '{@link nl.tue.glt.boundingBox.impl.MoveLeftImpl <em>Move Left</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.glt.boundingBox.impl.MoveLeftImpl
     * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getMoveLeft()
     * @generated
     */
    EClass MOVE_LEFT = eINSTANCE.getMoveLeft();

    /**
     * The meta object literal for the '{@link nl.tue.glt.boundingBox.impl.MoveRightImpl <em>Move Right</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.glt.boundingBox.impl.MoveRightImpl
     * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getMoveRight()
     * @generated
     */
    EClass MOVE_RIGHT = eINSTANCE.getMoveRight();

    /**
     * The meta object literal for the '{@link nl.tue.glt.boundingBox.impl.MoveUpImpl <em>Move Up</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.glt.boundingBox.impl.MoveUpImpl
     * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getMoveUp()
     * @generated
     */
    EClass MOVE_UP = eINSTANCE.getMoveUp();

    /**
     * The meta object literal for the '{@link nl.tue.glt.boundingBox.impl.MoveDownImpl <em>Move Down</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see nl.tue.glt.boundingBox.impl.MoveDownImpl
     * @see nl.tue.glt.boundingBox.impl.BoundingBoxPackageImpl#getMoveDown()
     * @generated
     */
    EClass MOVE_DOWN = eINSTANCE.getMoveDown();

  }

} //BoundingBoxPackage
