/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.boundingBox;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move Right</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.tue.glt.boundingBox.BoundingBoxPackage#getMoveRight()
 * @model
 * @generated
 */
public interface MoveRight extends MoveX
{
} // MoveRight
