/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.boundingBox;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move Y</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.tue.glt.boundingBox.BoundingBoxPackage#getMoveY()
 * @model
 * @generated
 */
public interface MoveY extends Move
{
} // MoveY
