/*
 * generated by Xtext 2.10.0
 */
package nl.tue.glt


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PlatoonRuntimeModule extends AbstractPlatoonRuntimeModule {
}
