/*
 * generated by Xtext 2.10.0
 */
package nl.tue.glt


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PlatoonStandaloneSetup extends PlatoonStandaloneSetupGenerated {

	def static void doSetup() {
		new PlatoonStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
