/*
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPlatoonScopeProvider extends DelegatingScopeProvider {
}
