/*
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractPlatoonValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(nl.tue.glt.platoon.PlatoonPackage.eINSTANCE);
		return result;
	}
	
}
