/*
 * generated by Xtext 2.10.0
 */
package nl.tue.glt.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import nl.tue.glt.ide.contentassist.antlr.internal.InternalPlatoonParser;
import nl.tue.glt.services.PlatoonGrammarAccess;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class PlatoonParser extends AbstractContentAssistParser {

	@Inject
	private PlatoonGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalPlatoonParser createParser() {
		InternalPlatoonParser result = new InternalPlatoonParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getVehicleAccess().getAlternatives(), "rule__Vehicle__Alternatives");
					put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
					put(grammarAccess.getTurnAccess().getAlternatives_1(), "rule__Turn__Alternatives_1");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getPlatoonAccess().getGroup(), "rule__Platoon__Group__0");
					put(grammarAccess.getFVAccess().getGroup(), "rule__FV__Group__0");
					put(grammarAccess.getLVAccess().getGroup(), "rule__LV__Group__0");
					put(grammarAccess.getRouteAccess().getGroup(), "rule__Route__Group__0");
					put(grammarAccess.getTurnAccess().getGroup(), "rule__Turn__Group__0");
					put(grammarAccess.getForwardAccess().getGroup(), "rule__Forward__Group__0");
					put(grammarAccess.getLeftAccess().getGroup(), "rule__Left__Group__0");
					put(grammarAccess.getRightAccess().getGroup(), "rule__Right__Group__0");
					put(grammarAccess.getConstraintsAccess().getGroup(), "rule__Constraints__Group__0");
					put(grammarAccess.getModelAccess().getPlatoonsAssignment_0(), "rule__Model__PlatoonsAssignment_0");
					put(grammarAccess.getModelAccess().getRoutesAssignment_1(), "rule__Model__RoutesAssignment_1");
					put(grammarAccess.getModelAccess().getConstraintsAssignment_2(), "rule__Model__ConstraintsAssignment_2");
					put(grammarAccess.getPlatoonAccess().getFirstAssignment_1(), "rule__Platoon__FirstAssignment_1");
					put(grammarAccess.getPlatoonAccess().getFollowersAssignment_2(), "rule__Platoon__FollowersAssignment_2");
					put(grammarAccess.getFVAccess().getNameAssignment_2(), "rule__FV__NameAssignment_2");
					put(grammarAccess.getFVAccess().getPulledByAssignment_5(), "rule__FV__PulledByAssignment_5");
					put(grammarAccess.getLVAccess().getNameAssignment_2(), "rule__LV__NameAssignment_2");
					put(grammarAccess.getLVAccess().getRouteAssignment_4(), "rule__LV__RouteAssignment_4");
					put(grammarAccess.getRouteAccess().getNameAssignment_1(), "rule__Route__NameAssignment_1");
					put(grammarAccess.getRouteAccess().getActionsAssignment_3(), "rule__Route__ActionsAssignment_3");
					put(grammarAccess.getForwardAccess().getDistanceAssignment_2(), "rule__Forward__DistanceAssignment_2");
					put(grammarAccess.getConstraintsAccess().getMinHeadwayAssignment_1(), "rule__Constraints__MinHeadwayAssignment_1");
					put(grammarAccess.getConstraintsAccess().getMaxHeadwayAssignment_5(), "rule__Constraints__MaxHeadwayAssignment_5");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalPlatoonParser typedParser = (InternalPlatoonParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PlatoonGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PlatoonGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
