/**
 * generated by Xtext 2.10.0
 */
package nl.tue.glt;

import nl.tue.glt.AbstractBoundingBoxRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class BoundingBoxRuntimeModule extends AbstractBoundingBoxRuntimeModule {
}
